package cli

import (
	"bytes"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// TestInstallSkillPrint_GoldenOutput executes install-skill --print with
// default flags and verifies the stdout contains key SKILL.md sections.
func TestInstallSkillPrint_GoldenOutput(t *testing.T) {
	root := NewRoot()
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs([]string{"install-skill", "--print"})

	if err := root.Execute(); err != nil {
		t.Fatalf("install-skill --print: %v\noutput: %s", err, buf.String())
	}

	out := buf.String()

	// Must contain YAML front-matter.
	if !strings.Contains(out, "name: codemap") {
		t.Errorf("output missing YAML front-matter 'name: codemap'")
	}
	// Must contain section headings.
	for _, heading := range []string{"# When to use", "# Commands", "# Output handling"} {
		if !strings.Contains(out, heading) {
			t.Errorf("output missing heading %q", heading)
		}
	}
	// Commands section must use "codemap" as the binary name (default).
	if !strings.Contains(out, "codemap status --json") {
		t.Errorf("output missing 'codemap status --json'")
	}
	// Must contain version marker footer.
	if !strings.Contains(out, "<!-- generated by codemap") {
		t.Errorf("output missing generated-by comment")
	}
}

// TestInstallSkillPrint_DoesNotWriteFile confirms --print does not create any file.
func TestInstallSkillPrint_DoesNotWriteFile(t *testing.T) {
	// We verify by checking that Install with print=true returns body, not path.
	// The CLI test simply executes and checks there's no error + no disk side effect.
	root := NewRoot()
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs([]string{"install-skill", "--print"})

	if err := root.Execute(); err != nil {
		t.Fatalf("install-skill --print returned error: %v", err)
	}

	out := buf.String()
	if strings.Contains(out, "installed:") {
		t.Error("--print should not emit 'installed:' path line")
	}
}

// TestInstallSkillCmd_Flags verifies the subcommand accepts expected flags.
func TestInstallSkillCmd_Flags(t *testing.T) {
	root := NewRoot()
	var found *cobra.Command // use loop to find
	for _, c := range root.Commands() {
		if c.Name() == "install-skill" {
			found = c
			break
		}
	}
	if found == nil {
		t.Fatal("install-skill subcommand not registered")
	}

	for _, flag := range []string{"scope", "agent", "print"} {
		if found.Flags().Lookup(flag) == nil {
			t.Errorf("flag --%s not registered on install-skill", flag)
		}
	}
}

// TestUninstallSkillCmd_Flags verifies the subcommand accepts expected flags.
func TestUninstallSkillCmd_Flags(t *testing.T) {
	root := NewRoot()
	var found *cobra.Command
	for _, c := range root.Commands() {
		if c.Name() == "uninstall-skill" {
			found = c
			break
		}
	}
	if found == nil {
		t.Fatal("uninstall-skill subcommand not registered")
	}

	for _, flag := range []string{"scope", "agent"} {
		if found.Flags().Lookup(flag) == nil {
			t.Errorf("flag --%s not registered on uninstall-skill", flag)
		}
	}
}
